console.log("it is working...");
var a = 100;
var b = 200.10;
var c = "Hello Test";
var d = null;
var e = ["Apple", "Mango", "Banana", 100];
console.log (a);
console.log (b);
console.log (c);
console.log (e.length);